#!/bin/bash
DIR="$(cd "$(dirname "$0")/../../../" && pwd)"
osascript << EOF
tell application "iTerm"
    activate
    if (count of windows) = 0 then
        create window with default profile
    end if
    tell current window
        create tab with default profile
        tell current session
            write text "cd '$DIR' && npm run dev:watch"
        end tell
    end tell
end tell
EOF
